version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    # hostname: es-master
    image: elasticsearch:7.6.0
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/master/data:/usr/share/elasticsearch/data
      - ./elasticsearch/master/logs:/usr/share/elasticsearch/logs
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.name=es-cluster"
      - "discovery.type=single-node"
    networks:
      - elk

  kibana:
    container_name: kibana
    image: kibana:7.6.0
    restart: always
    links:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - ./kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - "elasticsearch.hosts=http://elasticsearch:9200"
    networks:
      - elk
    depends_on:
      - elasticsearch


  logstash:
    container_name: logstash
    image: logstash:7.6.0
    command: logstash -f ./conf/logstash.conf
    restart: always
    volumes:
      - ./logstash/conf/logstash.conf:/usr/share/logstash/conf/logstash.conf
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
      - xpack.monitoring.elasticsearch.hosts=http://elasticsearch:9200
    ports:
      - 5044:5044
    networks:
      - elk
    depends_on:
      - elasticsearch


networks:
  elk:
    driver: bridge


volumes:
  elasticsearch:
